Repository openshift/csi-external-snapshotter, pull requests merged in 2020-03, with the labels that each got.

#15 Bug 1802467: Fix deletion of snapshots with Retain policy
  pkg/common-controller/framework_test.go
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshot_delete_test.go
  pkg/common-controller/snapshot_finalizer_test.go
  pkg/common-controller/snapshot_update_test.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#17 Bug 1808123: UPSTREAM 275: Allows VolumeSnapshot to be deleted if the class isn't found
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, bugzilla/valid-bug, kind/bug, lgtm

#16 Bug 1814280: UPSTREAM 278: Include a nil check for the snapshotContent
  pkg/common-controller/snapshot_controller.go
Labels: approved, bugzilla/valid-bug, kind/bug, lgtm

#19 Bug 1815563: UPSTREAM 278, 279: Include a nil check for the snapshotContent
  pkg/common-controller/snapshot_controller.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm

#18 Bug 1815500: UPSTREAM 275: Allows VolumeSnapshot to be deleted if the class isn't found
  pkg/common-controller/snapshot_controller.go
  pkg/common-controller/snapshot_controller_base.go
  pkg/common-controller/snapshot_create_test.go
  pkg/common-controller/snapshotclass_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm
